const UserRole = {
 // SUPER_ADMIN: 'SUPER_ADMIN',
  ADMINISTRATOR: 'ADMINISTRATOR',
  // PHYSICIAN: 'PHYSICIAN',
  // NURSE: 'NURSE',
  // COORDINATOR: 'COORDINATOR',
  // AUDITOR: 'AUDITOR',
  // PATIENT: 'PATIENT'
  EMPLOYEE: 'EMPLOYEE',
  MANAGER: 'MANAGER',
  HR_MANAGER: 'HR_MANAGER'
};

module.exports = { UserRole };
