apiVersion: v1
data:
  alerts.yml: |
    groups:
    - name: skillranker-alerts
      rules:
      - alert: BackendDown
        expr: up{job="skillranker-backend"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Backend SkillRanker DOWN"
          description: "Le backend SkillRanker ne répond plus"
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    alerting:
      alertmanagers:
        - static_configs:
            - targets: ['alertmanager:9093']
    rule_files:
      - /etc/prometheus/alerts.yml
    scrape_configs:
      - job_name: 'skillranker-backend'
        static_configs:
          - targets: ['skillranker-backend.skillranker.svc.cluster.local:3000']
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
