sonar.projectKey=SkillRanker
sonar.projectName=SkillRanker
sonar.sourceEncoding=UTF-8

sonar.sources=controllers,models,services
sonar.tests=Tests

sonar.test.inclusions=tests/**/*.test.js
sonar.exclusions=**/node_modules/**,**/coverage/**,**/uploads/**
sonar.coverage.exclusions=**/*.test.js,**/*.spec.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info
